CREATE GLOBAL TEMPORARY TABLE TEMP_TABL
(
	id varchar(50) NOT NULL
) ON COMMIT DELETE ROWS;

BEGIN
  SAVEPOINT start_tran;
  INSERT INTO TEMP_TABL (id)
  SELECT id FROM XX
  WHERE BB = XX; 

  DELETE FROM XX_X 
  WHERE id IN (
  	SELECT id from TEMP_TABL
  );  
 
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO start_tran;
    RAISE;
END;
